# Generated by Django 3.0.2 on 2020-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
